#!/usr/bin/perl -Ilib
#
# Sample to test work with Atmel ATF1500 family UIMs
#
# Copyright (c) 2025 Alexei A. Smekalkine <ikle@ikle.ru>
#
# SPDX-License-Identifier: BSD-2-Clause
#

use Atmel::F1500::UIM;
use Data::Dumper;

my @test = ('../led32ser', 'test/atf1502-pt-0', 'test/atf1502-pt-1');

my $name = $test[2];

my $jed = uim_read_jed (5, 40, $name);			# print Dumper $jed;
my $uim = uim_load     (5, 40, 'db/atmel/f1502/uim');	# print Dumper $uim;

uim_update ($uim, $name, $jed);				# print Dumper \$uim->[3];
uim_report ($uim);
uim_save   ($uim, 'db/atmel/f1502/uim');

